### ISSUE TITLE
[Question] Can the usage of this plugin hamper SEO of the site?

### ISSUE THREAD

**Issue by Nikhil-Ladha** [graysonhicks/gatsby-plugin-loadable-components-ssr#56]
If the page is split into smaller chunks can it hamper the SEO performance of the site?
Or, will the page will be still get crawled by google as it is since the page is SSR? If so, can I use the `loadable-components` on above-the-fold components too?

**Comment by Nikhil-Ladha** [comment]
@graysonhicks can you please help me with this question?

**Comment by graysonhicks** [comment]
Hi @Nikhil-Ladha!  No it should not hurt SEO performance *if* you are using this plugin.  The main function of this plugin is to maintain SSR with loadable so you keep the same SEO and static performance as before.  Without this plugin, yes, you would hurt SEO because those components that are chunked would be client side rendered.
